name: glimmora-one
region: blr

services:
  - name: api
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      repo: baarez-technology/Glimmora-One
      branch: main
      deploy_on_push: true
    http_port: 8080
    routes:
      - path: /v1
      - path: /uploads
    health_check:
      http_path: /health
    envs:
      - key: DATABASE_URL
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: BOOTSTRAP_SUPERADMIN_USERNAME
        value: superadmin
      - key: BOOTSTRAP_SUPERADMIN_PASSWORD
        type: SECRET
      - key: BOOTSTRAP_SUPERADMIN_EMAIL
        value: admin@glimmora.ai
      - key: JWT_EXPIRES_HOURS
        value: "24"
      - key: OPENAI_API_KEY
        type: SECRET
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: ALLOWED_ORIGINS
        value: ${APP_URL}

  - name: web
    dockerfile_path: apps/web/Dockerfile
    source_dir: /
    github:
      repo: baarez-technology/Glimmora-One
      branch: main
      deploy_on_push: true
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: BACKEND_URL
        value: ${api.PRIVATE_URL}
      - key: JWT_SECRET
        type: SECRET
